# Generated by Django 4.1.1 on 2024-01-10 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brain_Box_app', '0002_customtoken_quiz_topic_user_usertype_userhasusertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 10, 9, 34, 30, 593796, tzinfo=datetime.timezone.utc)),
        ),
    ]
